version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
      POSTGRES_DB: hotel_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
